version: '3'

services:
  postgres:
    image: "postgres:12"
    environment:
      POSTGRES_PASSWORD: "Zuppers"
      PGDATA: "/data/postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/data/postgres
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "marcos.ramalho@zup.com.br"
      PGADMIN_DEFAULT_PASSWORD: "Zuppers"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge